package com.bestarch.cart
 
import com.bestarch.cart.model.PurchaseAmount;
import com.bestarch.cart.model.Discount;
 
dialect "mvel"
 
rule "Apply discount when purchase amount < $5000"
	salience 10
    activation-group "x"
    when
        $amount : PurchaseAmount( $amount.baseAmount < 5000)
    then
        System.out.println("Processing amount "+ $amount.baseAmount );
        double deduction = 0;
        System.out.println("Deduction for this rule "+ deduction);
        Discount discount = new Discount();
        discount.setAmount(deduction);
       $amount.getApplicableDiscounts().add(discount);
end

/*
rule "GoodBye"
    when
        Message( status == Message.GOODBYE, myMessage : message )
    then
        System.out.println( myMessage );
end
*/